server {
    listen 3000;
    include /etc/nginx/mime.types;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Routing Flutter Web (clean URLs)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache pour assets statiques
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff|woff2|ttf)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Content Security Policy compatible Flutter Web
    add_header Content-Security-Policy "
        default-src 'self';
        script-src 'self' 'unsafe-eval' 'unsafe-inline' blob: https://www.gstatic.com;
        style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
        img-src 'self' data: blob:;
        font-src 'self' data: https://fonts.gstatic.com;
        connect-src *;
        worker-src 'self' blob:;
        child-src 'self' blob:;
    ";

    # Headers de sécurité supplémentaires
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
}