server {
    listen 3000;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy vers le backend NestJS
    location /api/ {
        proxy_pass http://host.docker.internal:4000/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # Forcer le navigateur à ne jamais utiliser un ancien service worker
    location = /flutter_service_worker.js {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }

    # Routing Flutter Web
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache pour assets statiques
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff|woff2|ttf)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }


    # Content Security Policy compatible Flutter Web
    add_header Content-Security-Policy "
        default-src 'self';
        script-src 'self' 'unsafe-eval' 'unsafe-inline' blob: https://www.gstatic.com;
        style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
        img-src 'self' data: blob:;
        font-src 'self' data: https://fonts.gstatic.com;
        connect-src *;
        worker-src 'self' blob:;
        child-src 'self' blob:;
    ";

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
}